### ISSUE TITLE
تشکر و پیشنهاد

### ISSUE THREAD

**Issue by Atn71** [MMDBadCoder/SSH-Tunnel-VPN-Server#1]
سلام دوست عزیز تا وقتی قسمت پرداخت ندیده بودم فکر نمی کردم ایرانی باشید
داشتم میگشتم همین طوری از اینجا سر درآوردم و خیلی خدشحالم
اول از همه یه گروه یا کانال باشه خیلی خوبه 
دوم اگر مقدور باشه محدودیت وصل شدن و ترافیک ادد بشه محشره
الان من از یک اسکریپت دیگه استفاده میکنم امتیازش نسبت به شما نمایش ترافیک و ادد کردن سرور دوم
اونم مثل شما تازه شروع کرده داره ابدیت میده ولی از پنل شما بیشتر خوشم اومد
البته اگر django Admin خوشگل تر فارسی بشه
البته اگر دوست داشتید منم تو فارسی سازی کمک کنم
سوم تنضیمات NapstrnetV و یا ssc برای اندروید در پنل کاربر که با اجازتون من این می خواستم اضافه منم
موفق باشید
, @atn0410217

**Comment by MMDBadCoder** [comment]
خیلی ممنون از فیدبکت
پیشنهادت جذاب بود برام
اضافت کردم
سلام برسون ب بچه ها :)
